aps_graph_compare.settings:
  type: config_object
  label: 'Client Configuration'
  mapping:
    comparison_keys:
      label: 'Comparison Keys'
      type: sequence
      sequence:
        type: mapping
        label: 'Comparison Key'
        mapping:
          primary:
            type: string
            label: 'Primary'
          secondary:
            type: string
            label: 'Secondary'
