_core:
  default_config_hash: FLJZME3II5fjmMSrdEvJHp95ZJf8V_X0jbX0VdVU1BU
shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: aps
    pass: xtV9M55k
allow_cli: true
debug_header: false
unset_basic_auth_headers: true
print: 'Please login to access the site'
method: 0
paths: ''
allowlist: ''
http_method_allowlist: {  }
domains: ''
